CREATE OR REPLACE VIEW VIEW_USUARIO_LIDER AS
    SELECT
        USERID AS ID,
        PASSWORD AS PASSWORD,
        IDLIDER AS CPI,
        NOME,
        CARGO,
        NACAO,
        ESPECIE
    FROM
        USERS U
    JOIN
        LIDER L ON U.IDLIDER = L.CPI;