

CREATE OR REPLACE PACKAGE PCT_RELATORIO_LIDER IS
    FUNCTION GERAR_RELATORIO_COMUNIDADES(V_LIDER LIDER.CPI%TYPE) RETURN VARCHAR2;
END PCT_COMUNIDADES;


CREATE OR REPLACE PACKAGE BODY PCT_RELATORIO_LIDER IS
    FUNCTION GERAR_RELATORIO_COMUNIDADES(V_LIDER LIDER.CPI%TYPE) RETURN VARCHAR2 IS
        V_SAIDA_RELATORIO VARCHAR2(32767) := 'COMUNIDADE;ESPECIE;PLANETA_HABITADO;FACCAO;NACAO' || CHR(10);
    BEGIN
        FOR R IN (
            SELECT DISTINCT
                C.NOME AS COMUNIDADE,
                C.ESPECIE AS ESPECIE,
                H.PLANETA AS PLANETA_HABITADO,
                NF.FACCAO AS FACCAO,
                NF.NACAO AS NACAO
            FROM 
                NACAO_FACCAO NF 
                JOIN FACCAO F ON NF.FACCAO = F.NOME
                JOIN PARTICIPA P ON F.NOME = P.FACCAO
                JOIN COMUNIDADE C ON P.COMUNIDADE = C.NOME AND P.ESPECIE = C.ESPECIE
                JOIN HABITACAO H ON C.NOME = H.COMUNIDADE AND C.ESPECIE = H.ESPECIE
            WHERE 
                F.LIDER = V_LIDER
            ORDER BY 
                C.NOME
        ) LOOP
            V_SAIDA_RELATORIO := V_SAIDA_RELATORIO || R.COMUNIDADE || ';' || R.ESPECIE || ';' || R.PLANETA_HABITADO || ';' || R.FACCAO || ';' || R.NACAO || CHR(10);
        END LOOP;
        
        RETURN V_SAIDA_RELATORIO;
    END GERAR_RELATORIO_COMUNIDADES;
END PCT_COMUNIDADES;


/* 
EXEMPLO DE CHAMADA DA FUNCAO

DECLARE
    V_LIDER LIDER.CPI%TYPE := '111.111.111-11';
    V_RELATORIO VARCHAR2(32767);
BEGIN
    V_RELATORIO := PCT_COMUNIDADES.GERAR_RELATORIO_COMUNIDADES(V_LIDER);
    DBMS_OUTPUT.PUT_LINE(V_RELATORIO);
END;

*/




