

CREATE OR REPLACE PACKAGE PCT_RELATORIO_LIDER IS
    FUNCTION GERAR_RELATORIO_COMUNIDADES(V_LIDER LIDER.CPI%TYPE) RETURN VARCHAR2;
END PCT_RELATORIO_LIDER;
/

CREATE OR REPLACE PACKAGE BODY PCT_RELATORIO_LIDER IS
    FUNCTION GERAR_RELATORIO_COMUNIDADES(V_LIDER LIDER.CPI%TYPE) RETURN VARCHAR2 IS
        V_SAIDA_RELATORIO VARCHAR2(32767) := 'COMUNIDADE;ESPECIE;PLANETA_HABITADO;FACCAO;NACAO' || CHR(10);
    BEGIN
        FOR R IN (
            SELECT 
                C.NOME AS COMUNIDADE,
                C.ESPECIE AS ESPECIE,
                H.PLANETA AS PLANETA_HABITADO,
                S.NOME AS SISTEMA,
                NF.FACCAO AS FACCAO,
                NF.NACAO AS NACAO
            FROM 
                NACAO_FACCAO NF 
                JOIN FACCAO F ON NF.FACCAO = F.NOME
                JOIN PARTICIPA P ON F.NOME = P.FACCAO
                JOIN COMUNIDADE C ON P.COMUNIDADE = C.NOME AND P.ESPECIE = C.ESPECIE
                JOIN HABITACAO H ON C.NOME = H.COMUNIDADE AND C.ESPECIE = H.ESPECIE
                JOIN ORBITA_PLANETA OP ON OP.PLANETA = H.PLANETA
                JOIN SISTEMA S ON S.ESTRELA = OP.ESTRELA
            WHERE 
                F.LIDER = V_LIDER
            GROUP BY 
                C.NOME,  C.ESPECIE, H.PLANETA, S.NOME, NF.FACCAO, NF.NACAO
        ) LOOP
            V_SAIDA_RELATORIO := V_SAIDA_RELATORIO || R.COMUNIDADE || ';' || R.ESPECIE || ';' || R.PLANETA_HABITADO || ';' || R.FACCAO || ';' || R.NACAO || CHR(10);
        END LOOP;
    EXCEPTION
            WHEN NO_DATA_FOUND THEN
                V_SAIDA_RELATORIO := 'Nenhum dado encontrado';
            WHEN OTHERS THEN
                V_SAIDA_RELATORIO := 'Erro ao gerar relatório';
        
        RETURN V_SAIDA_RELATORIO;
    END GERAR_RELATORIO_COMUNIDADES;
END PCT_RELATORIO_LIDER;


/* EXEMPLO DE CHAMADA DA FUNCAO

DECLARE
    V_LIDER LIDER.CPI%TYPE := '111.111.111-11';
    V_RELATORIO VARCHAR2(32767);
BEGIN
    V_RELATORIO := PCT_RELATORIO_LIDER.GERAR_RELATORIO_COMUNIDADES(V_LIDER);
    DBMS_OUTPUT.PUT_LINE(V_RELATORIO);
END;

*/




